// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7UoGaP8O5xY1cw1x-CvKukREqcJ5g7Q',
    appId: '1:473562240995:web:272665319f480f62cbb2d6',
    messagingSenderId: '473562240995',
    projectId: 'restaurants-b1d28',
    authDomain: 'restaurants-b1d28.firebaseapp.com',
    storageBucket: 'restaurants-b1d28.appspot.com',
    measurementId: 'G-0TH8WRWL69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8qCeeeAPi5eu1Z-Kbdo9f2NMIeQQZwc',
    appId: '1:473562240995:android:894e6220195c63fbcbb2d6',
    messagingSenderId: '473562240995',
    projectId: 'restaurants-b1d28',
    storageBucket: 'restaurants-b1d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dN6rF8LPAbjwdljBMycRylmkdx3GJGg',
    appId: '1:473562240995:ios:c27029acb1ebbf00cbb2d6',
    messagingSenderId: '473562240995',
    projectId: 'restaurants-b1d28',
    storageBucket: 'restaurants-b1d28.appspot.com',
    iosBundleId: 'com.example.kafrAldawarRestaurants',
  );
}
